### ISSUE TITLE
Is the reconstructed sequence a line or a loop?

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/smarty-plants#1]
From the Pevzner paper, it looks like they are applying Eulerian cycle-finding from linear fragments to construct a consistent linear sequence (DNA genome, or mRNA sequence).

<img width="452" alt="image" src="https://github.com/TheEvergreenStateCollege/smarty-plants/assets/148553/88bc49da-312e-421d-a930-91f6663d5f2d">

We can adapt our approach to either. This question we can delay until later when we get results to interpret.

**Comment by AbyssalRemark** [comment]
According to Nancy we definitely have a line. Only bacteria do circles. With very minima exceptions.
