### ISSUE TITLE
Record a screenshare video stepping through and narrating Ukkonen's algorithm

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/smarty-plants#35]
## Pre-requisites

1. You'll need to know Rust at the level of someone who has read, practiced, and answered questions through [The Rust Book up to Chapter 8](https://rust-book.cs.brown.edu/ch08-00-common-collections.html)

2. You'll need a computer with the Rust toolchain installed.

3. You'll need to know how to record a screenshare video, using software like Open Broadcasting Software (OBS) and upload it to a video sharing site like Youtube.

4. Clone, download, build, and run the repository for this issue

https://github.com/TheEvergreenStateCollege/smarty-plants

5. [You should be able to complete this previous task.](https://github.com/TheEvergreenStateCollege/smarty-plants/issues/34)

Please discuss your takeaways from the previous task in your application to this one.

## The Task

In a split screen display, have your IDE on one side with the code for the suffix tree loaded, starting on a breakpoint. On the other side, have this suffix tree visualizer with the input string "xabxac".

Start a screenshare video, using software like OBS.

Step through the code with a debugger for constructing the input string `abcabxabcd`.

Record a screenshare video where you narrate the steps as the code construct, adding watches or pointing out the value of variables accessible in the current scope where it's useful.

Upload this video to Youtube (or similar) and submit the video link as a comment to this task to complete this bounty.

**Comment by morukele** [comment]
I am interested in working on this. Is this still available, and what is the bounty reward?

**Comment by learner-long-life** [comment]
Thanks for your interest @morukele . The bounties were an experiment this past summer and are over now.
