### ISSUE TITLE
Git LFS and .gitignore

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/smarty-plants#47]
Currently the genome and FASTA files are committed into `data/` directory but are shown as tracked in Git large file support (LFS). However when cloning this repo for Ricard's private fork, it appears to automatically pull from LFS instead of requiring a separate step

```
git clone ...
git lfs pull
```

Are the large files actually committed into Git, outside of LFS, and can we add it to `.gitignore` to prevent accidental committing of large files in the future?

**Comment by AbyssalRemark** [comment]
OK. This is handled correctly. I don't think It pulls that data automatically. Maybe your computer ran out of space? or maybe something with your system is causing that to happen automagically? Either way, I cannot replicate this.
