### ISSUE TITLE
Write instructions to download fragments / genome

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/smarty-plants#5]
Google Drive doesn't allow curl, but it's possible to download the Mimosa pudica genome from NCBI per Gavin's link

(link to be added)

I'll move the old README.md into the `notes` folder and let's create a new shorter README.md file with download instructions,
to show teammates how to clone and bootstrap this software from scratch in a new dev environment.

**Comment by poperigby** [comment]
I just used Git LFS to add the data.

**Comment by learner-long-life** [comment]
This will make it more convenient to access.
However, We just used up 80% of our LFS quota for the GitHub org. 

Since the data is somewhat sensitive and there could be more data collected in the future, let’s hold off on adding more large files for now.

Sent from Yahoo Mail for iPhone


On Friday, April 19, 2024, 10:23 AM, PopeRigby ***@***.***> wrote:




I just used Git LFS to add the data.
