### ISSUE TITLE
Web user interface

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/smarty-plants#6]
@tw-edu is interested in this because graphic design is his passion.

<img src="https://github.com/TheEvergreenStateCollege/smarty-plants/assets/148553/61e5cb44-91f2-43ab-ba7a-151d74f65b43" width="200" />

We may be able to ship the genome with aligned reads to the web server, or write it into the database,
for biology researchers and other public users to access easily our results at a URL.

In the future, we can also let uses upload the FASTA fragment files via the same web UI.

**Comment by TW-Starbuyer** [comment]
![SmartyPlantsCardMockup](https://github.com/TheEvergreenStateCollege/smarty-plants/assets/156841820/ad4f0c16-e703-40ff-82e1-94f471e97cb5)

Logo concept side-quest #1

**Comment by learner-long-life** [comment]
This is being worked on in #36 now.
I'm using this logo in several places now, thanks @tw-edu
